apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservice
  annotations:
    # use the shared ingress-nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /api/playlists
        pathType: Prefix
        backend:
          service:
            name: mpe-service
            port:
              number: 4002
      - path: /api/my-playlists
        pathType: Prefix
        backend:
          service:
            name: mpe-service
            port:
              number: 4002
      - path: /api/events
        pathType: Prefix
        backend:
           service:
            name: mtv-service
            port:
              number: 4003
      - path: /api/my-events
        pathType: Prefix
        backend:
           service:
            name: mtv-service
            port:
              number: 4003
      - path: /api/tracks
        pathType: Prefix
        backend:
          service:
            name: tracks-service
            port:
              number: 4005
      - path: /api/*
        pathType: Prefix
        backend:
          service:
            name: users-service
            port:
              number: 4004
      - path: /api/media
        pathType: Prefix
        backend:
          service:
            name: sms-service
            port:
              number: 4006