apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-local-storage
  capacity:
    storage: 1Gi
  hostPath:
    path: /goinfre/mfilahi/mongodb